### ISSUE TITLE
Prewarmup SagaInfoCache and remove usage of ActiveSagaInstance

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Persistence.ServiceFabric#16]
Currently the saga persister uses ActiveSagaInstance.Instance.GetType() to determine the saga instance type in order to be able to call into SagaInfoCache and get the RuntimeSagaInfo. Relying on ActiveSagaInstance could potentially be avoided by warming up the SagaInfoCache in the saga persister feature like the following:

```
            var metadatas = settings.Get<SagaMetadataCollection>();
            foreach (var metadata in metadatas)
            {
                infoCache.GetInfo(metadata.SagaEntityType, metadata.SagaType);
            }
```

Sql Persistence could also adopt this. Still in the process of talking to @SimonCropp why Sql persister relies on ActiveSagaInstance intead of the approach outlined here. 

// cc @Particular/sqlpersistence-maintainers

**Comment by SimonCropp** [comment]
@danielmarbach i think since the sql persistence started before that api was exposed. but yes it is a better approach and we will try to get it in for v2

**Comment by danielmarbach** [comment]
@SimonCropp have a look https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/pull/18
