### ISSUE TITLE
Default Saga collection name is incorrect

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Persistence.ServiceFabric#29]
If no custom saga collection name is provide using  `ServiceFabricSaga` attribute

```c#
[ServiceFabricSaga(CollectionName = "custom-collection-name")]
```

Saga **type** name should be used. Currently, [Saga data type name](https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/blob/083776ebd92fe430ee1aa7d066ca4be1063d6805/src/NServiceBus.Persistence.ServiceFabric/Sagas/RuntimeSagaInfo.cs#L38)  is used.

The code

```c#
CollectionName = userProvidedAttribute?.CollectionName ?? sagaDataType.Name, 
```

should be

```c#
CollectionName = userProvidedAttribute?.CollectionName ?? sagaType.Name, 
```

**Comment by SeanFeldman** [comment]
cc @Particular/azure-maintainers

**Comment by danielmarbach** [comment]
That decision is entirely up to the persister and not standardized. We talked about it and concluded that sharing the data type is a nogo and there it is ok to use the data type. That's why the id is also derived from the datat type

**Comment by SeanFeldman** [comment]
👍 This is to avoid reliable collections name collisions. The doco should probably be explicit about that.

Replacing with doco issue https://github.com/Particular/docs.particular.net/issues/2686
