### ISSUE TITLE
Update to latest version of ServiceFabric

### ISSUE THREAD

**Issue by lexidev90** [Particular/NServiceBus.Persistence.ServiceFabric#336]
This package still requires <5 and is preventing us from updating our Service Fabric solution. I tried raising a support ticket and was directed here.

**Comment by mauroservienti** [comment]
@lexidev90 thanks for raising this. I've forwarded the issue internally to the relevant group for triage.

**Comment by abarnybox** [comment]
Hiya, just wondering if there was a timescale on this at all? :)

**Comment by mikeminutillo** [comment]
@abarnybox it's on our radar but I can't give a definitive timeframe on it at this stage. Can I ask what features of ServiceFabric 5 you are looking to take advantage of?

**Comment by WojcikMike** [comment]
We made the change to reference ServiceFabric (5.1) in the next major release of this package. There is no eta when we will release it, but at least the change is already made: https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/pull/412

**Comment by danielmarbach** [comment]
We have released version 2.6 which targets Microsoft.ServiceFabric.Data 5.x range and 2.7 which targets the recently released 6.x target. 

https://discuss.particular.net/t/nservicebus-persistence-servicefabric-2-6-0-and-2-7-0-minor-releases-available/3026
