### ISSUE TITLE
Enable support for .NET Core

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Persistence.ServiceFabric#56]
SF SDK 3.0 has support for .NET Core.
The project should be updated to provide support for it (release 3.1).

**Comment by SeanFeldman** [comment]
This is not blocking RC and we could release it as 2.1.0

**Comment by danielmarbach** [comment]
Done as part of https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/pull/104
